# Import the search agent, reader agent, writer chain and critic chain
from agents import build_search_agent, build_reader_agent, writer_chain, critic_chain


# Main function that runs all steps of the research pipeline
# topic : research topic entered by the user
# -> dict : function returns the final state dictionary
def run_research_pipeline(topic: str) -> dict:

    # Create an empty dictionary to store results from every step
    state = {}

    # STEP-1 Search agent working:
    # Create the Search Agent
    search_agent = build_search_agent()

    # Run the Search Agent and give it the research topic
    search_result = search_agent.invoke({
        "messages": [
            ("user", f"Find recent, reliable and detailed information about: {topic}")
        ]
    })

    # Get the last message returned by the agent
    # .content gives the actual text of that message
    # Save the search result inside the "state" dictionary
    state['search_results'] = search_result['messages'][-1].content

    # Print the search results
    print("\n search result ", state['search_results'])


    # step-2 Reader Agent:
    # Create the Reader Agent
    reader_agent = build_reader_agent()

    # Run the Reader Agent
    # Give it the search results from Step 1
    reader_result = reader_agent.invoke({
        "messages": [(
            "user",
            f"Based on the following search results about '{topic}', "
            f"pick the most relevant URL and scrape it for deeper content.\n\n"
            f"Search Results:\n{state['search_results'][:800]}"
        )]
    })

    # Get the last message from the Reader Agent
    # Save its content as scraped research
    state['scraped_content'] = reader_result['messages'][-1].content

    # Print the scraped content
    print("\nscraped content: \n", state['scraped_content'])


    # step 3 - writer chain:
    # Combine search results and scraped content
    # so the Writer Chain can use all the research
    research_combined = (
        f"SEARCH RESULTS : \n {state['search_results']} \n\n"
        f"DETAILED SCRAPED CONTENT : \n {state['scraped_content']}"
    )

    # Run the Writer Chain
    # Pass the topic and combined research to it
    state["report"] = writer_chain.invoke({
        "topic": topic,
        "research": research_combined
    })

    # Print the generated report
    print("\n Final Report\n", state['report'])


    # step 4: Run the Critic Chain
    # Give it the report generated by the Writer Chain
    state["feedback"] = critic_chain.invoke({
        "report": state['report']
    })

    # Print the critic's feedback
    print("\n critic report \n", state['feedback'])

    # Return all stored results
    return state


# Check whether this file is being run directly
if __name__ == "__main__":

    # Ask the user to enter a research topic
    topic = input("\n Enter a research topic : ")

    # Start the complete research pipeline
    run_research_pipeline(topic)